"""empty message

Revision ID: 3033b819a3f0
Revises: ca737d69b416
Create Date: 2022-09-23 15:53:05.072362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3033b819a3f0'
down_revision = 'ca737d69b416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='user avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='user avatar')
    # ### end Alembic commands ###
