"""empty message

Revision ID: 9fe2d9e6f250
Revises: ec269fdce6eb
Create Date: 2022-09-24 09:48:10.036770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe2d9e6f250'
down_revision = 'ec269fdce6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('replied_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['replied_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'replied_id')
    # ### end Alembic commands ###
