"""empty message

Revision ID: be6feeb71b7c
Revises: b1120388f891
Create Date: 2022-09-23 09:09:18.597734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be6feeb71b7c'
down_revision = 'b1120388f891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=40), nullable=True, comment='user password'))
    # ### end Alembic commands ###
