"""empty message

Revision ID: c8398f5da146
Revises: 97dab6f2be29
Create Date: 2022-09-23 13:17:49.513303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8398f5da146'
down_revision = '97dab6f2be29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
