"""empty message

Revision ID: ca737d69b416
Revises: 2a1d63c93fd4
Create Date: 2022-09-23 15:50:57.512298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca737d69b416'
down_revision = '2a1d63c93fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=100), nullable=False, comment='user avatar'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
