"""empty message

Revision ID: ec269fdce6eb
Revises: fc4dfed487e8
Create Date: 2022-09-24 09:44:51.442423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec269fdce6eb'
down_revision = 'fc4dfed487e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_3', 'comment', type_='foreignkey')
    op.drop_column('comment', 'replied_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('replied_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_ibfk_3', 'comment', 'comment', ['replied_id'], ['id'])
    # ### end Alembic commands ###
