"""empty message

Revision ID: fc4dfed487e8
Revises: 863ba85849e1
Create Date: 2022-09-24 09:36:20.629563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4dfed487e8'
down_revision = '863ba85849e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('replied_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['replied_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'replied_id')
    # ### end Alembic commands ###
